# Generated by Django 5.1.4 on 2024-12-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Event Name')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('organizer', models.CharField(max_length=255, verbose_name='Organizer')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Event Description')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
    ]
