# Generated by Django 5.1.4 on 2024-12-15 11:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(max_length=255, verbose_name=accounts.models.User),
        ),
    ]
